<html>
<head><meta charset="utf-8"><title>ubuntu 18.04→20.04 psycopg2 error · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html">ubuntu 18.04→20.04 psycopg2 error</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="1316338"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316338" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316338">(Jan 26 2022 at 14:22)</a>:</h4>
<p>I am running Zulip 4.9 (just upgraded this morning from 4.5 -- no issues with that) on Ubuntu 18.04.</p>
<p>I followed &lt;<a href="https://zulip.readthedocs.io/en/4.9/production/upgrade-or-modify.html#upgrading-from-ubuntu-18-04-bionic-to-20-04-focal">https://zulip.readthedocs.io/en/4.9/production/upgrade-or-modify.html#upgrading-from-ubuntu-18-04-bionic-to-20-04-focal</a>&gt; and all is well until step 5, the reindexing step. For step 4, upgrading postgresql, I get:</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# /home/zulip/deployments/current/scripts/setup/upgrade-postgresql
Already running PostgreSQL 13!
</code></pre></div>
<p>and then for the index regeneration, I get</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# /home/zulip/deployments/current/scripts/setup/reindex-textual-data --force
Traceback (most recent call last):
  File &quot;/home/zulip/deployments/current/scripts/setup/reindex-textual-data&quot;, line 9, in &lt;module&gt;
    import psycopg2
ModuleNotFoundError: No module named &#39;psycopg2&#39;
</code></pre></div>
<p>What should I do at this point? Do I just <code>pip install psycopg2</code> and try again? It seems like this error is unexpected and may be indicative of errors down the line. Has anyone else encountered this? Advice?</p>



<a name="1316339"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316339" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316339">(Jan 26 2022 at 14:26)</a>:</h4>
<p>As a follow-up, I ran <code>pip install psycopg2</code> and tried again, and got this error:</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# /home/zulip/deployments/current/scripts/setup/reindex-textual-data --force
Traceback (most recent call last):
  File &quot;/home/zulip/deployments/current/scripts/setup/reindex-textual-data&quot;, line 16, in &lt;module&gt;
    setup_path()
  File &quot;/home/zulip/deployments/current/scripts/setup/../../scripts/lib/setup_path.py&quot;, line 20, in setup_path
    raise RuntimeError(venv + &quot; was not set up for this Python version&quot;)
RuntimeError: /home/zulip/deployments/current/zulip-py3-venv was not set up for this Python version
</code></pre></div>
<p>So the pip install was not a quick fix.</p>



<a name="1316342"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316342" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316342">(Jan 26 2022 at 14:37)</a>:</h4>
<p>After the pip install, I tried did <code>rm -rf /srv/zulip-venv-cache/</code> followed by <code>/home/zulip/deployments/current/scripts/lib/create-production-venv /home/zulip/deployments/current</code> as suggested <a href="https://github.com/zulip/zulip/issues/12065#issuecomment-495963297">here</a>. After than, the <code>reindex-textual-data</code> command worked. Now on to step 6...</p>



<a name="1316344"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316344" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316344">(Jan 26 2022 at 14:39)</a>:</h4>
<p>Darn, another error:</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# /home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2 \
&gt;     /home/zulip/deployments/current/ --ignore-static-assets --audit-fts-indexes
...
Error: Execution of &#39;/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python3-psycopg2&#39; returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-psycopg2 : Depends: python3 (&lt; 3.7) but 3.8.2-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: /Stage[main]/Zulip::Process_fts_updates/Zulip::Safepackage[python3-psycopg2]/Package[python3-psycopg2]/ensure: change from &#39;purged&#39; to &#39;present&#39; failed: Execution of &#39;/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python3-psycopg2&#39; returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-psycopg2 : Depends: python3 (&lt; 3.7) but 3.8.2-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
Notice: /Stage[main]/Zulip::Process_fts_updates/File[/etc/supervisor/conf.d/zulip/zulip_db.conf]: Dependency Package[python3-psycopg2] has failures: true
Warning: /Stage[main]/Zulip::Process_fts_updates/File[/etc/supervisor/conf.d/zulip/zulip_db.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Zulip::Supervisor/Service[supervisor]: Skipping because of failed dependencies
Warning: /Stage[main]/Zulip::Supervisor/Exec[supervisor-restart]: Skipping because of failed dependencies
Notice: Applied catalog in 3.58 seconds
Traceback (most recent call last):
  File &quot;/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2&quot;, line 352, in &lt;module&gt;
    subprocess.check_call([&quot;./scripts/zulip-puppet-apply&quot;, &quot;--force&quot;])
  File &quot;/usr/lib/python3.8/subprocess.py&quot;, line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command &#39;[&#39;./scripts/zulip-puppet-apply&#39;, &#39;--force&#39;]&#39; returned non-zero exit status 1.
</code></pre></div>



<a name="1316345"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316345" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316345">(Jan 26 2022 at 14:42)</a>:</h4>
<p>I get the same error as above if I precede the <code>upgrade-zulip-stage-2</code> command with <code>rm -rf /srv/zulip-venv-cache/*</code>. Darn. Any suggestions?</p>



<a name="1316349"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316349" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316349">(Jan 26 2022 at 15:07)</a>:</h4>
<p>Another note for troubleshooting: I am using the Zulip Digital Ocean droplet (<a href="https://marketplace.digitalocean.com/apps/zulip">https://marketplace.digitalocean.com/apps/zulip</a>). Well, the one that was configured for zulip 4.5 on ubuntu 18.04.</p>



<a name="1316373"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316373" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316373">(Jan 26 2022 at 15:53)</a>:</h4>
<p>when I get apt info for python3-psycopg2, I see</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# apt info python3-psycopg2 -a
Package: python3-psycopg2
Version: 2.8.6-2~pgdg18.04+1
Depends: python3 (&lt;&lt; 3.7), python3 (&gt;= 3.6~), python3:any (&gt;= 3.3.2-2~), libc6 (&gt;= 2.15), libpq5 (&gt;= 10~~)
APT-Sources: http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages
...
Package: python3-psycopg2
Version: 2.8.4-2
Depends: python3 (&lt;&lt; 3.9), python3 (&gt;= 3.8~), python3:any, libc6 (&gt;= 2.15), libpq5 (&gt;= 10~~)
APT-Sources: http://mirrors.digitalocean.com/ubuntu focal/main amd64 Packages
...
</code></pre></div>
<p>and then</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# apt-cache policy python3-psycopg2
python3-psycopg2:
  Installed: (none)
  Candidate: 2.8.6-2~pgdg18.04+1
  Version table:
     2.8.6-2~pgdg18.04+1 500
        500 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages
     2.8.4-2 500
        500 http://mirrors.digitalocean.com/ubuntu focal/main amd64 Packages
</code></pre></div>
<p>It seems that zulip is preferring the <a href="http://postgresql.org">postgresql.org</a> version:</p>
<div class="codehilite"><pre><span></span><code>root@zulip:~# cat /etc/apt/sources.list.d/zulip.list.distUpgrade
deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
deb-src http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main

deb http://ppa.launchpad.net/groonga/ppa/ubuntu bionic main
deb-src http://ppa.launchpad.net/groonga/ppa/ubuntu bionic main
</code></pre></div>
<div class="codehilite"><pre><span></span><code>root@zulip:~# cat /etc/apt/sources.list.d/zulip.list
deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
deb-src http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main

deb http://ppa.launchpad.net/groonga/ppa/ubuntu focal main
deb-src http://ppa.launchpad.net/groonga/ppa/ubuntu focal main
</code></pre></div>
<p>This seems normally fine, but in this case, the candidate python3-psycopg2 package appears to require python &lt; 3.7 ? Not sure what to do here. Temporarily disable  <code>/etc/apt/sources.list.d/zulip.list*</code> ?</p>



<a name="1316377"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316377" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Donny Winston <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316377">(Jan 26 2022 at 16:00)</a>:</h4>
<p>Okay, disabling the zulip apt sources appears to have solved the problem. I did this:</p>
<div class="codehilite"><pre><span></span><code># as root
mv /etc/apt/sources.list.d/zulip.list* ~/
apt-get update
apt-cache policy python3-psycopg2 # verify by eye that the right package will be fetched
/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2 /home/zulip/deployments/current/ --ignore-static-assets --audit-fts-indexes
</code></pre></div>
<p>and my server is up and running. I then ran</p>
<div class="codehilite"><pre><span></span><code>mv ~/zulip.list* /etc/apt/sources.list.d/
apt-get update
</code></pre></div>
<p>to restore that stuff as before. But, I guess I may need to move them again on the next dist upgrade.</p>
<p>I hope this helps others. Any advice that is less convoluted than my procedure is appreciated. :)</p>



<a name="1316435"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316435" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anders Kaseorg <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316435">(Jan 26 2022 at 19:27)</a>:</h4>
<p>Try <code>/srv/zulip-py3-venv/bin/python /home/zulip/deployments/current/scripts/setup/reindex-textual-data</code>.</p>
<p>(Opened <a href="https://github.com/zulip/zulip/pull/20933">#20933</a> to make that unnecessary.)</p>



<a name="1316454"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316454" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316454">(Jan 26 2022 at 20:10)</a>:</h4>
<p>We should backport those commits to <code>4.x</code>, right?</p>



<a name="1316459"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316459" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alex Vandiver <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316459">(Jan 26 2022 at 20:14)</a>:</h4>
<p>They're flagged for backport, yes.</p>



<a name="1316468"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316468" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anders Kaseorg <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316468">(Jan 26 2022 at 20:19)</a>:</h4>
<p>I figure we can backport the first one, and revert the second one when we make the next release.</p>



<a name="1316473"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316473" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anders Kaseorg <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316473">(Jan 26 2022 at 20:24)</a>:</h4>
<p>Unless we want to update <a href="https://zulip.readthedocs.io/en/stable/">https://zulip.readthedocs.io/en/stable/</a> from the 4.x branch?</p>



<a name="1316483"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316483" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anders Kaseorg <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316483">(Jan 26 2022 at 20:31)</a>:</h4>
<p>We <a href="https://docs.readthedocs.io/en/stable/versions.html">could do that</a> if our 4.x branch was named <code>stable</code>.</p>



<a name="1316489"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/ubuntu%2018.04%E2%86%9220.04%20psycopg2%20error/near/1316489" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/ubuntu.2018.2E04.E2.86.9220.2E04.20psycopg2.20error.html#1316489">(Jan 26 2022 at 20:34)</a>:</h4>
<p>I think we're probably going to do a 4.10 release soon enough that it's not worth extra gymnastics.</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>