<html>
<head><meta charset="utf-8"><title>Zulip Traceback error while restarting  [s3 file upload ] · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Zulip.20Traceback.20error.20while.20restarting.20.20.5Bs3.20file.20upload.20.5D.html">Zulip Traceback error while restarting  [s3 file upload ]</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="763661"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Zulip%20Traceback%20error%20while%20restarting%20%20%5Bs3%20file%20upload%20%5D/near/763661" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lucas Peixoto <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Zulip.20Traceback.20error.20while.20restarting.20.20.5Bs3.20file.20upload.20.5D.html#763661">(Jul 04 2019 at 14:37)</a>:</h4>
<p><a href="/user_uploads/2/96/yqzxh2Hjrs-wvHTCbgVYfeir/Screen-Shot-2019-07-04-at-11.34.14.png" target="_blank" title="Screen-Shot-2019-07-04-at-11.34.14.png">Screen-Shot-2019-07-04-at-11.34.14.png</a> </p>
<div class="message_inline_image"><a href="/user_uploads/2/96/yqzxh2Hjrs-wvHTCbgVYfeir/Screen-Shot-2019-07-04-at-11.34.14.png" target="_blank" title="Screen-Shot-2019-07-04-at-11.34.14.png"><img src="/user_uploads/2/96/yqzxh2Hjrs-wvHTCbgVYfeir/Screen-Shot-2019-07-04-at-11.34.14.png"></a></div><p>So guys, I've followed all the steps from "File upload backends" to set a s3 bucket for that. and I'm getting those traceback error while restarting the server.<br>
Zulip version = 2.0.4 [docker-compose deploy]</p>



<a name="763700"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Zulip%20Traceback%20error%20while%20restarting%20%20%5Bs3%20file%20upload%20%5D/near/763700" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Zulip.20Traceback.20error.20while.20restarting.20.20.5Bs3.20file.20upload.20.5D.html#763700">(Jul 04 2019 at 15:13)</a>:</h4>
<p><span class="user-mention" data-user-id="12863">@Lucas Peixoto</span> that traceback usually means <code>/etc/zulip/zulip-secrets.conf</code> is not configured properly.  With Docker, I'd look at the <code>SECRETS_secret_key</code> variable.</p>



<a name="763704"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Zulip%20Traceback%20error%20while%20restarting%20%20%5Bs3%20file%20upload%20%5D/near/763704" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lucas Peixoto <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Zulip.20Traceback.20error.20while.20restarting.20.20.5Bs3.20file.20upload.20.5D.html#763704">(Jul 04 2019 at 15:17)</a>:</h4>
<p><span class="user-mention" data-user-id="7">@Tim Abbott</span> I figured it out some way, after applying changes with "/home/zulip/deployments/current/scripts/zulip-puppet-apply". It seems that /etc/zulip/zulip-secrets.conf  somehow loses its link to /data/zulip-secrets.conf. So I just re linked it and it was ok. Should I open an issue for that?</p>



<a name="763884"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Zulip%20Traceback%20error%20while%20restarting%20%20%5Bs3%20file%20upload%20%5D/near/763884" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Zulip.20Traceback.20error.20while.20restarting.20.20.5Bs3.20file.20upload.20.5D.html#763884">(Jul 04 2019 at 23:38)</a>:</h4>
<p><span class="user-mention" data-user-id="12863">@Lucas Peixoto</span> sure, open an issue, though it'd be 10x better if you can figure out what you did to get into that situation.</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>