[
    {
        "content": "<p>Hi all</p>\n<p>This is zulip-server-6.0-rc1 on Ubuntu 22.04.1 LTS.</p>\n<ol>\n<li>\n<p>Opened the <a href=\"https://chat.xyz.com/new/52agapsfxwz6lzpqfqweu2fh\">https://chat.xyz.com/new/52agapsfxwz6lzpqfqweu2fh</a> on a browser.</p>\n</li>\n<li>\n<p>Created the Zulip organization with the admin user, but ended with showing internal errors on Zulip.</p>\n</li>\n<li>\n<p>Tried to login as admin user, but cannot login.</p>\n</li>\n<li>\n<p>NOTE: Did not configure the out going email server settings. We don't have a one yet.</p>\n</li>\n<li>\n<p>auth.log shows:<br>\n2022-11-06 09:29:42.478 INFO [zulip.auth.email] Authentication attempt from 192.168.1.120: subdomain=;username=xyz@gmail.com;outcome=failed;return_data={}</p>\n</li>\n<li>\n<p>errors.log shows:<br>\nFollowing message shows repeatedly:<br>\nConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN.</p>\n</li>\n</ol>\n<p>What can be the issue?</p>",
        "id": 1460023,
        "sender_full_name": "Configentia",
        "timestamp": 1667728082
    },
    {
        "content": "<p>Here is the new update on this:</p>\n<ol>\n<li>\n<p>Removed Zulip. Recreated the database.</p>\n</li>\n<li>\n<p>Reinstalled Zulip and configured Gmail SMTP settings in /etc/zulip/settings.py before generate_realm_creation_link.</p>\n</li>\n<li>\n<p>Opened the new link on a browser to register a new Zulip organization. NOTE:  Still shows internal errors develop on Zulip server side.</p>\n</li>\n<li>\n<p>I did not receive an email for the new admin registration.</p>\n</li>\n<li>\n<p>I clicked on the \"Forgot your password?\" and I get an email saying my email has no account on the Zulip server.</p>\n</li>\n</ol>\n<p>Any ideas?</p>",
        "id": 1460030,
        "sender_full_name": "Configentia",
        "timestamp": 1667742603
    },
    {
        "content": "<p>This topic was moved here from <a class=\"stream-topic\" data-stream-id=\"9\" href=\"/#narrow/stream/9-issues/topic/Admin.20cannot.20login.20after.20Zulip.20organization\">#issues &gt; Admin cannot login after Zulip organization</a> by <span class=\"user-mention silent\" data-user-id=\"19257\">Alya Abbott</span>.</p>",
        "id": 1460246,
        "sender_full_name": "Notification Bot",
        "timestamp": 1667838235
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"25125\">@Configentia</span> Can you show the full recent <code>errors.log</code> content? Sounds like Zulip maybe be unable to connect to the database or some other component? Not sure without the full log messages</p>",
        "id": 1460262,
        "sender_full_name": "Mateusz Mandera",
        "timestamp": 1667838890
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"10349\">@Mateusz Mandera</span> Thanks for the reply. Let me do clean re-installation and upload the errors.log.</p>",
        "id": 1460721,
        "sender_full_name": "Configentia",
        "timestamp": 1667883962
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"25125\">@Configentia</span> I think it's still likely to be useful without needing a re-install, so feel free to just show that as well</p>",
        "id": 1460802,
        "sender_full_name": "Mateusz Mandera",
        "timestamp": 1667904012
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"10349\">@Mateusz Mandera</span> Sorry HDD crashed :) Waiting replacement arrives. I can get the log today itself.</p>",
        "id": 1460803,
        "sender_full_name": "Configentia",
        "timestamp": 1667904180
    },
    {
        "content": "<p>\"ConnectionClosedByBroker\" is a RabbitMQ failure, for reference.</p>",
        "id": 1460944,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1667922162
    },
    {
        "content": "<p>But if the HDD has now crashed ,that may explain some of the bad state that server managed to get into previously.</p>",
        "id": 1460945,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1667922296
    },
    {
        "content": "<p>But if rabbitmq continues to be the issue, I'd check <code>rabbitmqctl status</code>, and if that loosk fine, reset the auth via <code>scripts/setup/configure-rabbitmq</code> as root</p>",
        "id": 1460947,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1667922355
    },
    {
        "content": "<p>After install the new hard disk, it worked! Now playing with Zulip <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span> Thanks everyone for helping on this.</p>",
        "id": 1461557,
        "sender_full_name": "Configentia",
        "timestamp": 1667999708
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"25125\">Configentia</span> has marked this topic as resolved.</p>",
        "id": 1461558,
        "sender_full_name": "Notification Bot",
        "timestamp": 1667999729
    }
]