[
    {
        "content": "<p>Logger root, from module zerver.tornado.event_queue line 494:<br>\nError generated by Anonymous user (not logged in) on chatserver deployment</p>\n<p>Traceback (most recent call last):<br>\n  File \"/home/zulip/deployments/2020-11-25-13-11-57/zerver/tornado/event_queue.py\", line 490, in load_event_queues<br>\n    data = ujson.load(stored_queues)<br>\nValueError: Expected object or value</p>",
        "id": 1070717,
        "sender_full_name": "Jenish",
        "timestamp": 1606465888
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"17897\">@Jenish</span> what side effects are you facing due to this error?</p>",
        "id": 1070748,
        "sender_full_name": "Aman (amanagr)",
        "timestamp": 1606480756
    },
    {
        "content": "<p>Please specify how you came across this error and what command were you running?</p>",
        "id": 1070749,
        "sender_full_name": "Aman (amanagr)",
        "timestamp": 1606480812
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"5140\">@Aman Agrawal</span>  I got this mail from zulip random timing</p>",
        "id": 1071106,
        "sender_full_name": "Jenish",
        "timestamp": 1606536589
    }
]