[
    {
        "content": "<p>Posting <a href=\"https://github.com/zulip/zulip/pull/24131\">#24131</a> here for visibility:</p>\n<blockquote>\n<p>Following the guide at <a href=\"http://zulip.com/help/import-from-mattermost\">zulip.com/help/import-from-mattermost</a></p>\n<p>I have exported data from Mattermost<br>\nI was able to run convert_mattermost_data</p>\n<p>Attempting the import of the converted data runs across duplicate key value errors such as below:</p>\n<p>django.db.utils.IntegrityError: duplicate key value violates unique constraint \"zerver_recipient_type_type_id_29712363_uniq\"<br>\nDETAIL: Key (type, type_id)=(3, 74) already exists.</p>\n<p>I attempted to edit the realm.json file and removed the mentioned values just to get through the import for testing but that just leads to another error time and time again.</p>\n<p>I'm unsure where to go from here.</p>\n</blockquote>",
        "id": 1494723,
        "sender_full_name": "Alya Abbott",
        "timestamp": 1674461197
    },
    {
        "content": "<p>This certainly sounds like a bug where we're creating two huddles with the same set of users, rather than a single one? <span class=\"user-mention\" data-user-id=\"10349\">@Mateusz Mandera</span> can you take care of investigating this with the user?</p>",
        "id": 1495543,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1674526373
    }
]