[
    {
        "content": "<p>I just tried to run the upgrade to the latest release on our production server (2.1.2) and got 2 errors<br>\nCollecting talon==1.2.10.zulip1<br>\n  Using cached <a href=\"https://github.com/zulip/talon/archive/7d8bdc4dbcfcc5a73298747293b99fe53da55315.zip\">https://github.com/zulip/talon/archive/7d8bdc4dbcfcc5a73298747293b99fe53da55315.zip</a><br>\n    ERROR: Command errored out with exit status 1:<br>\n     command: /srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-uwbslaie/talon/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-uwbslaie/talon/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-install-uwbslaie/talon/pip-egg-info<br>\n         cwd: /tmp/pip-install-uwbslaie/talon/<br>\n    Complete output (7 lines):<br>\n    Traceback (most recent call last):<br>\n      File \"&lt;string&gt;\", line 1, in &lt;module&gt;<br>\n      File \"/tmp/pip-install-uwbslaie/talon/setup.py\", line 9, in &lt;module&gt;<br>\n        long_description=open(\"README.rst\").read(),<br>\n      File \"/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/python3.6/encodings/ascii.py\", line 26, in decode<br>\n        return codecs.ascii_decode(input, self.errors)[0]<br>\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 475: ordinal not in range(128)<br>\n    ----------------------------------------<br>\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.<br>\nWARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.<br>\nYou should consider upgrading via the 'pip install --upgrade pip' command.</p>\n<p>Error running a subcommand of /home/zulip/deployments/2020-07-16-05-09-40/scripts/lib/create-production-venv: /srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/bin/pip install --no-deps --require-hashes --requirement /home/zulip/deployments/2020-07-16-05-09-40/requirements/prod.txt<br>\nActual error output for the subcommand is just above this.</p>",
        "id": 938548,
        "sender_full_name": "Steven",
        "timestamp": 1594877424
    },
    {
        "content": "<p>Here is the full log for more info <a href=\"/user_uploads/2/d5/TV8Ci-et_PJ-Y5EWCEvpKy3c/ZulipUpgradeLog.txt\">ZulipUpgradeLog.txt</a></p>",
        "id": 938558,
        "sender_full_name": "Steven",
        "timestamp": 1594877462
    },
    {
        "content": "<p>The production server seems fine and still running the 2.1.2 version however I would like to be able to upgrade it.</p>",
        "id": 938563,
        "sender_full_name": "Steven",
        "timestamp": 1594877512
    },
    {
        "content": "<p>any help is appreciated</p>",
        "id": 938566,
        "sender_full_name": "Steven",
        "timestamp": 1594877540
    },
    {
        "content": "<p>Yeah this is sort of known; it was triggered by Ubuntu releasing a glibc security upgrade, but I think the actual problem is that we’re doing some buggy manual manipulation of locales in the installer script.</p>",
        "id": 938570,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594877572
    },
    {
        "content": "<p>If you just run the upgrade again I think it will work.</p>",
        "id": 938572,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594877583
    },
    {
        "content": "<p>ok I will attempt and report back</p>",
        "id": 938583,
        "sender_full_name": "Steven",
        "timestamp": 1594877669
    },
    {
        "content": "<p>Great, I’m interested to hear what happens.</p>",
        "id": 938586,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594877686
    },
    {
        "content": "<p>same result as the first log, 2 errors the same as the first time.. Now I see apt-get updated the kernel as well and I have not done a reboot. I'm wondering if I need to reboot the server and try the upgrade again?</p>",
        "id": 938604,
        "sender_full_name": "Steven",
        "timestamp": 1594877861
    },
    {
        "content": "<p>Hmm okay. Run <code>dpkg-reconfigure locales</code> and enable the <code>en_US.UTF-8</code> locale, that should fix it for good.</p>",
        "id": 938638,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594878122
    },
    {
        "content": "<p>ok will try and report back</p>",
        "id": 938641,
        "sender_full_name": "Steven",
        "timestamp": 1594878144
    },
    {
        "content": "<p>(Rebooting at some point is a good idea so the kernel security upgrade takes effect, but shouldn’t be needed to get the installer working.)</p>",
        "id": 938658,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594878280
    },
    {
        "content": "<p>The setting of the locales seems to have done the trick!</p>",
        "id": 938699,
        "sender_full_name": "Steven",
        "timestamp": 1594878650
    },
    {
        "content": "<p>TY.. I will schedule a reboot over the weekend however for now everything seems to be running and upgraded</p>",
        "id": 938702,
        "sender_full_name": "Steven",
        "timestamp": 1594878676
    },
    {
        "content": "<p>Thank you for your great and prompt assistance</p>",
        "id": 938703,
        "sender_full_name": "Steven",
        "timestamp": 1594878691
    },
    {
        "content": "<p>No problem!</p>",
        "id": 938704,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594878703
    },
    {
        "content": "<p>Filed <a href=\"https://github.com/zulip/zulip/pull/15819\">#15819</a> for what I think is going on here.</p>",
        "id": 938834,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1594879500
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"699\">Anders Kaseorg</span> <a href=\"#narrow/stream/31-production-help/topic/upgrade.20from.202.2E1.2E2/near/938638\">said</a>:</p>\n<blockquote>\n<p>Hmm okay. Run <code>dpkg-reconfigure locales</code> and enable the <code>en_US.UTF-8</code> locale, that should fix it for good.</p>\n</blockquote>\n<p>This helped me as well to upgrade form 2.0.2</p>",
        "id": 955271,
        "sender_full_name": "Matthias",
        "timestamp": 1595751590
    }
]